repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-added-large-files
        - id: check-symlinks
        - id: destroyed-symlinks
        - id: check-vcs-permalinks
        - id: detect-aws-credentials
          args: [--allow-missing-credentials]
        - id: detect-private-key
        - id: no-commit-to-branch
